In [3]:
!pip install numpy

In [17]:
#---------Single--Dimensional--Array---------
import numpy as np
n1 = np.array([10,20,30])
n1

array([10, 20, 30])

In [16]:
#initializing numpy array using zero
import numpy as np
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [19]:
#initializing numpy array with same number
import numpy as np
n1 = np.full((2,2), 10)
n1

array([[10, 10],
       [10, 10]])

In [24]:
#array within a range
import numpy as np
n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
#initialize with a random number
import numpy as np
n1 = np.random.randint(1,100,5) #here 5 presents that random terms
n1

array([23, 62, 53, 29, 33])

In [31]:
#checking shape of array
import numpy as np
n1 = np.array([(1, 4, 7), (2, 9, 5)])
print("Original shape:", n1.shape)
n1.shape = (3, 2)
print("New shape:", n1.shape)
print(n1)


Original shape: (2, 3)
New shape: (3, 2)
[[1 4]
 [7 2]
 [9 5]]


In [40]:
#joining numpy arrays
import numpy as np
n1 = np.array([10,20,30,40])
n2 = np.array([50,60,70,80])
np.vstack((n1, n2))  #vertical stack(v-stack)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [39]:
import numpy as np
n1 = np.array([10,20,30,40])
n2 = np.array([50,60,70,80])
np.hstack((n1,n2)) #horizontal stack

array([10, 20, 30, 40, 50, 60, 70, 80])

In [1]:
import numpy as np
n1 = np.array([10,20,30,40])
n2 = np.array([50,60,70,80])
np.column_stack((n1,n2))

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [4]:
import numpy as np
n1 = np.array([12,34,56,78])
n2 = np.array([50,60,70,80])
print(np.intersectionId(n1,n2))

AttributeError: module 'numpy' has no attribute 'intersectionId'